// @flow

export const UPDATE_OPTIONS = 'UPDATE_OPTIONS'

export const ADD_PLAYER_TO_OPTIONS = 'ADD_PLAYER_TO_OPTIONS'

export const REMOVE_PLAYER_FROM_OPTIONS = 'REMOVE_PLAYER_FROM_OPTIONS'

export const START_GAME_FROM_OPTIONS = 'START_GAME_FROM_OPTIONS'

